services:
  - type: web
    name: n8n
    runtime: node  # Spécifie que le service utilise Node.js
    runtimeVersion: "18.17.0"  # Force la version de Node.js à 18.17.0

    # --- Variables d'environnement ---
    envVars:
      # Configuration de base de n8n
      - key: PORT
        value: "5678"
      - key: N8N_LOG_LEVEL
        value: "info"  # Corrigé : une seule valeur (au lieu de verbose et info)
      - key: GENERIC_TIMEZONE
        value: "Europe/Paris"
      - key: TZ
        value: "fr"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_URL
        sync: false

      # Activation des nœuds et packages communautaires
      - key: N8N_COMMUNITY_PACKAGES_ENABLED
        value: "true"
      - key: N8N_COMMUNITY_NODES_ENABLED
        value: "true"
      - key: N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE
        value: "true"
      - key: N8N_COMMUNITY_PACKAGES_INSTALL_TIMEOUT
        value: "60000"  # Timeout de 60 secondes pour l'installation des packages

databases:
  - name: n8nDB  # Crée une base de données PostgreSQL pour n8n